name: Deploy Client

on:
  push:
    branches: [main, vite_client]
    paths: "client/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - run: yarn install --frozen-lockfile
        working-directory: ./client
      - run: yarn build
        working-directory: ./client
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./client/build
